### PR TITLE
add windows packaging scripts

### PR DESCRIPTION
**Pull request by eyedeekay**
This re-adds about 75% of what go-anonvpn was doing with NSIS for windows packaging, and removes the experimental parts. It should make the VPN easier to install on windows and automatically kick off an I2P installer if an I2P router isn't already present on the system.

### CODE REVIEW

**Review by bonedaddy — CHANGES_REQUESTED** [review]
`make nsis` fails with the following error

```
wget -c https://github.com/PurpleI2P/i2pd/releases/download//setup_i2pd_v.exe -O i2pdinstaller.exe
--2020-02-19 11:25:38--  https://github.com/PurpleI2P/i2pd/releases/download//setup_i2pd_v.exe
Resolving github.com (github.com)... 140.82.114.3
Connecting to github.com (github.com)|140.82.114.3|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-19 11:25:38 ERROR 404: Not Found.

make: *** [geti2p.mk:42: i2pdinstaller.exe] Error 8
```

**Comment by eyedeekay** [comment]
Hmm... This part of the build system gets the current version of i2pd by asking for it from the github API, and it uses gothub to do this. I should probably just add it to the Makefile and update it at release time instead.

**Comment by bonedaddy** [comment]
Sorry for the delayed response, was in vegas and just getting caught up on things. With your new changes more progress but another error:
```
nsis/wintap.exe                                      100%[=====================================================================================================================>] 574.15K   943KB/s    in 0.6s    

2020-02-23 14:12:22 (943 KB/s) - ‘nsis/wintap.exe’ saved [587928/587928]

makensis nsis/installer.nsi
Processing config: /etc/nsisconf.nsh
Processing script file: "nsis/installer.nsi" (UTF8)
File: "../cmd/anonvpn/anonvpn.exe" -> no files found.
Usage: File [/nonfatal] [/a] ([/r] [/x filespec [...]] filespec [...] |
   /oname=outfile one_file_only)
Error in script "nsis/installer.nsi" on line 28 -- aborting creation process
make: *** [Makefile:95: winstall] Error 1
```

**Comment by bonedaddy** [comment]
More progress, but another error:

```
2020-02-23 19:06:29 (698 KB/s) - ‘nsis/wintap.exe’ saved [587928/587928]

makensis nsis/installer.nsi
Processing config: /etc/nsisconf.nsh
Processing script file: "nsis/installer.nsi" (UTF8)
File: "../cmd/anonvpn/anonvpn-32.exe" -> no files found.
Usage: File [/nonfatal] [/a] ([/r] [/x filespec [...]] filespec [...] |
   /oname=outfile one_file_only)
Error in script "nsis/installer.nsi" on line 30 -- aborting creation process
make: *** [Makefile:95: winstall] Error 1
```

**Comment by bonedaddy** [comment]
> More progress, but another error:
> 
> ```
> 2020-02-23 19:06:29 (698 KB/s) - ‘nsis/wintap.exe’ saved [587928/587928]
> 
> makensis nsis/installer.nsi
> Processing config: /etc/nsisconf.nsh
> Processing script file: "nsis/installer.nsi" (UTF8)
> File: "../cmd/anonvpn/anonvpn-32.exe" -> no files found.
> Usage: File [/nonfatal] [/a] ([/r] [/x filespec [...]] filespec [...] |
>    /oname=outfile one_file_only)
> Error in script "nsis/installer.nsi" on line 30 -- aborting creation process
> make: *** [Makefile:95: winstall] Error 1
> ```

Still getting this error, looks like it might not be properly creating the exe file? Or is one of my dependencies out of date?

**Comment by eyedeekay** [comment]
It's that it expects a 32-bit windows build to be present but it doesn't appear to be in the make target for ```make nsis```. Running ```make windows windows-32 nsis``` should work. 64-bit systems still use 64-bit builds, but we send a 32-bit copy along too in and detect which one to use at install time. I didn't check the ```windows``` target, I thought that it built both.

**Comment by bonedaddy** [comment]
Running `make windows windows-32 nsis`

Gave me the error:

```
$ make windows windows-32 nsis
syso -o cmd/anonvpn/out.syso
successfully generated syso file to cmd/anonvpn/out.sysoGOARCH=amd64 GOOS=windows go build -a -tags=" netgo static" \
	-buildmode=exe \
	-o cmd/anonvpn/anonvpn.exe \
	./cmd/anonvpn
rm -f cmd/anonvpn/out.syso
make: *** No rule to make target 'windows-32'.  Stop.
```

However `make windows nsis` worked

**Comment by eyedeekay** [comment]
No hyphen, that's my bad ```make windows windows32 nsis```. But I did add them to the ```make nsis``` target so it will work on it's own now.

**Comment by bonedaddy** [comment]
Ah ok not a problem!

**Review by bonedaddy — APPROVED** [review]
good work

**Pull request merged**
